# The items in this configuration file correspond to the steps in the overall recipe.
# The values refer to configuration files of the individual steps.

defaults:
  - .@paths: ../paths
  - .@shared: ../shared
  - .@setup: setup
  - .@validate: validate
  - .@prepare: prepare
  - .@enhance: enhance
  - .@evaluate: evaluate
  - .@report: report
  - _self_

# Info for which signals to evaluate
segment_types: [individual] # [individual, summed] # Types of reference segments to process
devices: [aria] # Devices to process
dataset: dev # Dataset to use for processing
sample_rate: 16000

# Setting up paths for outputs of the experiments
base_dir: ${paths.scratch}/experiments/${shared.exp_name}
hydra:
  run:
    dir: ${base_dir}/hydra
  job_logging:
    root:
      level: INFO

# If you wish to skip a step, set its value to null or true as below.
# This can be also done from command-line when running the script, e.g.
# python run.py setup.run=false
setup:
  run: true
enhance:
  run: true
validate:
  run: true
prepare:
  run: true
evaluate:
  run: true
report:
  run: true
