epochs: 100
checkpoint_interval: 2
lr: 1e-6
clip_grad_norm: 1.0

schedule_lr:
  name: plateau_reduce
  params:
    mode: min
    factor: 0.5
    patience: 2
    threshold: 0.1
    min_lr: 1e-08

loss:
  name: spec
  kwargs:
    fft_size: 1024
    hop_size: 256
    win_length: 1024
    window: hann_window
    w_sc: 1.0
    w_log_mag: 1.0
    w_lin_mag: 0.0
    w_phs: 0.0
    sample_rate: null
    scale: null
    n_bins: null
    perceptual_weighting: false
    scale_invariance: false
    eps: 1.0e-08
    output: loss
    reduction: mean
    mag_distance: L1