noisy_input_file: ${..paths.echi_signal}
rainbow_input_file: ${..paths.rainbow_signal_file}
ref_input_file: ${..paths.ref_signal_file}
segment_info_file: ${..paths.segment_info_file}

model_sample_rate: ${..model_sample_rate}
ref_sample_rate: ${..ref_sample_rate}

noisy_output_dir: ${..paths.train_input_dir}
rainbow_output_file: ${..paths.train_rainbow_file}
ref_output_dir: ${..paths.train_target_dir}

dataset: [train, dev]
devices: ${..device}
sessions_file: ${..paths.sessions_file}
