sessions_file: ${..paths.sessions_file}

device: ${device}
dataset: ${dataset}

noisy_signal: ${..paths.inference_device_file}
rainbow_signal: ${..paths.inference_rainbow_file}
enhanced_signal: ${..paths.enhanced_signal}

model_sample_rate: ${..shared.model_sample_rate}
ref_sample_rate: ${..shared.ref_sample_rate}
bitdepth: ${..shared.signal_bitdepth}
